apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-shop-blue
  namespace: miztiik-automation-ns
  labels:
    name: miztiik-automation
    project: eks-external-dns-with-route53
    app: k-shop-blue
    role: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: miztiik-automation
      role: blue
  template:
    metadata:
      labels:
        name: miztiik-automation
        role: blue
    spec:
      containers:
        - name: k-shop-blue-nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80