apiVersion: v1
kind: Pod
metadata:
  name: k-shop-reader
  namespace: miztiik-automation-ns
  labels:
    project: eks-external-dns-with-route53
    app: k-shop-reader
    role: reader
spec:
  containers:
  - name: k-shop-reader
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /shared
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-storage-claim